name: MinecraftRegionStats
version: '1.0-SNAPSHOT'
main: me.dammnranaah.minecraftregionstats.Main
api-version: 1.20

commands:
  specialstats:
    description: Display the stats of the region.
    usage: /specialstats
    permission: specialstats.use

permissions:
  specialstats.use:
    description: Allows players to use the specialstats command.
    default: true
